# Schema for the configuration files of the Ice Cream theme.

club_theme.settings:
  type: theme_settings
  label: 'Club Theme settings'
  mapping:
    site_branding_bg_color:
      type: string
      label: 'Site branding background color'