# Schema for the configuration files of the hello_world module.
hello_world.settings:
  type: config_object
  label: 'hello_world settings'
  mapping:
    example:
      type: string
      label: 'Example'
